### ISSUE TITLE
Develop a Builder tutorial for class use

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#100]
Create a BCO using publication **Communicating regulatory high-throughput sequencing data using BioCompute Objects. Drug Discov Today. 2022 Jan 22; PMID: [35077912](https://pubmed.ncbi.nlm.nih.gov/35077912/).** Then make a tutorial as an example for students

**Comment by kee007ney** [comment]
First draft by Friday June 30th.

**Comment by tiwa1154** [comment]
https://biocomputeobject.org/builder?https://biocomputeobject.org/BCO_000368/DRAFT

**Comment by kee007ney** [comment]
Version 2 by Wednesday, July 5th.

**Comment by kee007ney** [comment]
Will compare to Chinweoke's BCO.

**Comment by kee007ney** [comment]
@HadleyKing and me to review.

**Comment by ChinweokeO** [comment]
https://biocomputeobject.org/builder?https://biocomputeobject.org/BCO_000369/DRAFT

**Comment by ChinweokeO** [comment]
The BCOs need to be compared by @HadleyKing and @kee007ney as they are intended for classroom use.
