### ISSUE TITLE
BCO Validation Error - Step number not being recognized as integer

### ISSUE THREAD

**Issue by Jgergely11** [biocompute-objects/portal_userdb#105]
**Describe the bug**
I am unable to validate ARGOS_000019 due to an error where an integer is not being recognized as an integer for the "step number" in the description domain. 

I have the exact same issue with ARGOS_000018

**Expected behavior**
I expect the BCO to be validated because the values are integers 

**Screenshots**
![image](https://github.com/biocompute-objects/portal_userdb/assets/96205065/96582818-661d-428f-8cc5-b99efd09d5dd)

**Comment by HadleyKing** [comment]
Will need to force the proper type for the BCO if it is not.

**Comment by HadleyKing** [comment]
Fixed with [Builder css](https://github.com/biocompute-objects/portal_userdb/commit/44aee85c8a4a23ff9ba201afb61bf3417a96a941)
