### ISSUE TITLE
"save" function not working besides provenance domain - could be clarification issue

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#113]
**Describe the bug**
"save" function not clear. Need to indicate the save function only saves to the web browser but doesn't update the backend BCO. Need to click '''Update BCO''' to actually save the changes.

**Comment by HadleyKing** [comment]
Change button to "next"

**Comment by tiwa1154** [comment]
https://github.com/biocompute-objects/portal_userdb/pull/127
