### ISSUE TITLE
403 error message on saved draft

### ISSUE THREAD

**Issue by penningtonea** [biocompute-objects/portal_userdb#114]
**Describe the bug**
I searched for a BCO that I saved as a draft and have previously been able to access but received an error message pasted below in the screenshots section.

**To Reproduce**
I logged in, I used advanced search to search for My BCOs, keyword for the search was "DRM". The search pulled up the BCO I was looking for, but when I clicked on the link for ARGOS_000055DRAFT I received the error message. After clicking "OK" on the error message I could see that the BCO was empty where all of the information had been saved previously.

**Expected behavior**
The BCO should have been there with all of the information that was previously saved

**Screenshots**
![image](https://github.com/biocompute-objects/portal_userdb/assets/70979519/cb5e724f-da15-4bc8-8656-f305da91e2c3)

**Desktop (please complete the following information):**
Windows 10
Chrome browser

**Comment by penningtonea** [comment]
Issue resolved by logging out and back in. My username appeared in the upper right corner of the screen so I assumed I was logged in.

**Comment by HadleyKing** [comment]
There is not yet a good notification system for users when the login token expires. I will close this issue but https://github.com/biocompute-objects/portal_userdb/issues/119 will track that.
