### ISSUE TITLE
Tasks for Chinweoke

### ISSUE THREAD

**Issue by kee007ney** [biocompute-objects/portal_userdb#126]

**Comment by kee007ney** [comment]
- Draft another BCO for classroom (and compare to Tianyi's)
- Update builder tutorial
- Testing for 23.07

**Comment by tiwa1154** [comment]
For the class-use tutorial, refer to this ticket: https://github.com/biocompute-objects/portal_userdb/issues/100

**Comment by ChinweokeO** [comment]
Issues with finding path for URIs
