### ISSUE TITLE
AI/ML Module at BioCompute Workshop

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#133]
For 2024 BioCompute workshop we should have a session on AI/ML and role of BioCompute in shining light in the black box... We need to invite VA congressman who is getting a MS degree in AI/ML

Create a SP page with ideas

**Comment by tiwa1154** [comment]
https://gwu0.sharepoint.com/:w:/r/sites/BioCompute-GRP/Shared%20Documents/Workshop/[2024BioComputeWorkshop.docx](https://gwu0.sharepoint.com/:w:/r/sites/BioCompute-GRP/Shared%20Documents/Workshop/2024BioComputeWorkshop.docx?d=wae0739a5894947a5874b44a22bd7b85a&csf=1&web=1&e=PmE3EJ)?d=wae0739a5894947a5874b44a22bd7b85a&csf=1&web=1&e=PmE3EJ

**Comment by ChinweokeO** [comment]
Waiting for review from @kee007ney

**Comment by ChinweokeO** [comment]
https://gwu0.sharepoint.com/:w:/r/sites/BioCompute-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BAD96B5E5-6F85-4377-B816-06501E122474%7D&file=2024%20BioCompute%20Workshop%20Ideas.docx&action=default&mobileredirect=true
