### ISSUE TITLE
Prefix Error

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/portal_userdb#134]
**Describe the bug**
Network error when trying to select a prefix. 

**To Reproduce**
1. Go to 'https://test.portal.biochemistry.gwu.edu/'
2. Click on 'BCO builder'
3. Scroll down and select 'Tools'
4. Click on 'Get Prefixes'

**Expected behavior**
It lags a little bit, then shows this  error: 'Request failed with status code 500'

**Screenshots**

![Screenshot 2023-07-18 092047](https://github.com/biocompute-objects/portal_userdb/assets/127264259/8f80b72e-fc4a-42d8-8cbe-5bd2f29d46ed)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Home
 - Chrome
 - Version: NA

**Comment by HadleyKing** [comment]
The request URL is incorrect. This is probably because the settings file is not configured correctly. 
`Request URL:
http://127.0.0.1:8000/api/prefixes/token/`
