### ISSUE TITLE
Password Reset/Change

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/portal_userdb#136]
**Describe the bug**
Unable to change password while in the account or reset password while on sign in page

**To Reproduce**
1. Go to 'https://portal.biochemistry.gwu.edu/'
2. Click on 'log in'
3. Select '[Don't have an account? Sign up here]'
4. Nothing happens, no email is sent/received
5. If signed in, click on name at top right
6. Click change password
7. Enter Old password and new password you would like to change to
8. Error: Request failed with status code 401

**Expected behavior**
Email should be sent for resetting password, and changing password should not result in error

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Comment by HadleyKing** [comment]
Fixed with 608c2664e63590fbe5a247999144135871cfede4
