### ISSUE TITLE
Windows Specific Local Deployment

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal_userdb#146]
Using https://github.com/biocompute-objects/portal_userdb/blob/main/docs/localDeployment.md try to deploy the code for the UI and UserDb in a Windows environment. Update the README as needed.

**Comment by ChinweokeO** [comment]
Edited branch here:  
https://github.com/biocompute-objects/portal_userdb/blob/windos_deployment/docs/localDeployment.md
