### ISSUE TITLE
Uploaded BCO parsing prefix from the object_ID

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#148]
**Describe the bug**
When a pre-populated BCO is uploaded to the Builder portal, it's parsing the object_ID incorrectly to get the prefix causing prefix permission errors

**To Reproduce**
1. Go to Builder
2. Click on Upload a BCO
3. Click on UPDATE DRAFT
4. See error message
![Screen Shot 2023-08-03 at 12 05 56](https://github.com/biocompute-objects/portal_userdb/assets/90009613/a44ca309-1b2c-4e28-83bc-b3a8d5fb9dad)

**To fix for now**
After uploading the BCO, click on Derive button, choose BCODB, prefix and save draft

**Desktop (please complete the following information):**
 - Browser [Firefox]
 - Version [23.07]

**Comment by HadleyKing** [comment]
https://github.com/biocompute-objects/portal_userdb/pull/176
