### ISSUE TITLE
content must be served over HTTPS

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal_userdb#149]
For the extension domain the extension schema is blocked if it is not an `https` address. 

> extension.js:16 Mixed Content: The page at 'https://biocomputeobject.org/builder?https://biocomputeobject.org/GLY_000143/DRAFT' was loaded over HTTPS, but requested an insecure resource 'http://www.w3id.org/biocompute/extension_domain/1.2.0/dataset/dataset_extension.json'. This request has been blocked; the content must be served over HTTPS.

We will need to provide a notification or other solution

**Comment by tiwa1154** [comment]
Modify Failed notification message and add a link to the FAQs
