### ISSUE TITLE
Galaxy BCO draft directed to local host URI

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#154]
**Describe the bug**
When accessing GALXY_000019/DRAFT and GALXY_000020/DRAFT, both of them direct to local host URL (https://biocomputeobject.org/builder?http://127.0.0.1:8000/GALXY_000019/DRAFT). Both of the BCOs were created using the DERIVE BCO function. Error see screenshot: ![Screen Shot 2023-08-08 at 11 16 18](https://github.com/biocompute-objects/portal_userdb/assets/90009613/4fa615dc-26c9-42b0-987b-761c894b7762)

**To Reproduce**
1. Go to GALXY_000019/DRAFT or GALXY_000020/DRAFT
2. See error "Network error"

**Desktop (please complete the following information):**
 - Browser [Firefox
 - Version [23.07]

**Additional context**
@HadleyKing has changed both of the URLs from the admin site. Fixed two places: in the contents and in the object_id field

**Comment by HadleyKing** [comment]
This was due to a settings issue with the server and resolved.

**Comment by tiwa1154** [comment]
https://biocomputeobject.org/builder?https://biocomputeobject.org/GALXY_000025/DRAFT also ran into the same issue. How should I resolve this on my end? @HadleyKing
