### ISSUE TITLE
Send out workshop email and calendar

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#170]

**Comment by tiwa1154** [comment]
Create a SP, list all key stakeholders dnanexus, FDA, GW, Velsera, key people in the past and present who have supported us for example Jonas, Gil etc.

Share in slack to get approval first

**Comment by tiwa1154** [comment]
https://gwu0.sharepoint.com/sites/BioCompute-GRP/_layouts/15/doc.aspx?sourcedoc={76cf8f45-9d64-427c-b534-86ed65946ccf}&action=edit

**Comment by ChinweokeO** [comment]
https://gwu0.sharepoint.com/:x:/r/sites/BioCompute-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B27F7D2A6-ED2D-4725-9CB0-001EE537F736%7D&file=Workshop%20Invite%20List.xlsx&action=default&mobileredirect=true

**Comment by kee007ney** [comment]
@kee007ney to review list of potential attendees, then send to Raja.
