### ISSUE TITLE
Tests for UserDB APIs

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal_userdb#184]
- [x] #207
- [ ] #185
- [ ] #186
- [ ] #187
- [ ] #188
- [ ] #189
- [ ] #190
- [ ] #191
- [ ] #192
- [ ] #193
- [ ] #194
- [ ] #195
- [ ] #196
- [ ] #197
- [ ] #198
- [ ] #199
- [x] #200
- [ ] #201
- [ ] #202
- [ ] #203
- [ ] #204
- [ ] #205
- [ ] #206
- [x] #246
- [x] #247
- [x] #248

**Comment by Reeya123** [comment]
Do we close this issue? @HadleyKing 

Not sure how much we progressed with these.
