### ISSUE TITLE
Unable to change profile info in User Profile

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#222]
**Describe the bug**
Unable to modify first/last name in User Profile after logging in (not ORCID)

**To Reproduce**
1. Click on username after logging in
2. Modify Last/First name

**Expected behavior**
Successfully changes the profile info.

**Screenshots**
![Screen Shot 2023-10-11 at 13 05 54](https://github.com/biocompute-objects/portal_userdb/assets/90009613/2f24aaf2-49a5-403c-8b62-9d2963dd5eb9)

**Desktop (please complete the following information):**
 - Browser [Fairfox]

**Comment by HadleyKing** [comment]
Resolved with fixes to DB files
