### ISSUE TITLE
Workshop Preparation

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/portal_userdb#230]
- [ ] #170 
- [ ] #228 
- [ ] Send out Eventbrite to DNAnexus and Velsera for feedback and ask them to register
- [ ] Finalize planning committee
- [ ] Define roles and responsibilities for planning committee members

**Comment by tiwa1154** [comment]
Workshop planning & workflow and milestone doc: https://gwu0.sharepoint.com/:w:/r/sites/BioCompute-GRP/Shared%20Documents/Workshop/2024%20workshop/2024%20BioCompute%20Workshop%20planning.docx?d=w5a20b8da76ce4ae1a732d97839d4687d&csf=1&web=1&e=C5SUBq
