### ISSUE TITLE
About Page update

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#24]
Update the About page, push to test and production

1. Go through documentation for updating the front end
2. Mission section
3. Move members to 'Former' section after they leave
4. Add citation/new publication

**Comment by kee007ney** [comment]
Still working on it, pushed to 4/21.

**Comment by kee007ney** [comment]
Most recent pushed to GH (`tianyi` branch).

**Comment by kee007ney** [comment]
(Under portal_userdb)
