### ISSUE TITLE
403 Error when selecting BCODB

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/portal_userdb#252]
**Describe the bug**
Selecting server leads to a 403 error. Please see screenshot

**To Reproduce**
1. Go to ''biocomputeobject.org
2. Click on 'Builder'
3. At the top of screen click 'Select BCODB' 
4. Select server
5. See 403 error

**Screenshots**
![Screenshot 2023-11-27 163053](https://github.com/biocompute-objects/portal_userdb/assets/127264259/51646f98-24b7-4c7b-a02c-ca3fa02cb973)

**Desktop (please complete the following information):** 
 - Browser [Google Chrome]
 - Version [119.0.6045.124]
 - HP

**Comment by HadleyKing** [comment]
need to have additional error handeling here for missing DB

**Comment by tiwa1154** [comment]
I think this is fixed, I am closing the ticket
