### ISSUE TITLE
Find an example paper from the journal `Database` to use as a template

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal_userdb#282]

**Comment by ChinweokeO** [comment]
Example Papers
https://academic.oup.com/database/article/doi/10.1093/database/baab019/6244733?searchresult=1
https://academic.oup.com/database/article/doi/10.1093/database/baw154/2884891?searchresult=1
https://academic.oup.com/database/article/doi/10.1093/database/baac035/6591806?searchresult=1
