### ISSUE TITLE
Update Roadmap

### ISSUE THREAD

**Issue by kee007ney** [biocompute-objects/portal_userdb#32]

**Comment by HadleyKing** [comment]
Expand API 
- CFDE-PP integration APIs May14-June23
- SBG Integration APIs June4-july2
- DNAnexus Integration APIs June4-july2

Imporve UI
- Viewer formatting May7-June25
- Builder formatting - July2-Agust20
- BCODB search formatting August6-27
- Prefix page formatting july2-30
- Groups page formatting june4-25
