### ISSUE TITLE
BCO curation for potential LLM training

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#323]
Selected paper can be found at https://gwu0.sharepoint.com/:x:/r/sites/BioCompute-GRP/_layouts/15/Doc.aspx?sourcedoc=%7BA9CB327E-76BC-45CE-9FB1-EBF81DD11575%7D&file=Papers%20to%20BCOs.xlsx&action=default&mobileredirect=true

- https://github.com/biocompute-objects/portal_userdb/issues/307

**Comment by ChinweokeO** [comment]
Search for workflows that have therapeutic intervention
