### ISSUE TITLE
Unable to sign into BioCompute

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/portal_userdb#336]
**Describe the bug**
I get a 502 error when I try to sign in with any of my credentials, or google sign in. I have also tried to clear my cache and cookies, and tried Google Chrome and Microsoft Edge. 

**To Reproduce**
1. Go to 'https://test.portal.biochemistry.gwu.edu/login'
2. Put in BioCompute test credentials
3. It gives me an error on both browsers.
4. I tried signing with my google but received the same error. 

**Expected behavior**

**Screenshots**
It should have signed me in

**Desktop (please complete the following information):**
 - Browser: Microsoft Edge and Google Chrome

**Comment by tiwa1154** [comment]
@ChinweokeO I believe it's because you were not connected to the test server when you tested
