### ISSUE TITLE
Publishing BCO through JSON

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/portal_userdb#337]
**Describe the bug**
![image](https://github.com/biocompute-objects/portal_userdb/assets/127264259/3ab2ee96-a09a-4a2c-bd67-362e2a768a1f)

This is what it shows when trying to publish a BCO through raw JSON. However, I was still able to find the BCO in the DB. It just says it is not in the server but it is. 

**To Reproduce**
1. Paste an exemplar BCO JSON into Raw JSON view 
2. Validate BCO
3. Publish BCO

**Expected behavior**
It does validate the BCO but does not show that the BCO has been published.

**Comment by tiwa1154** [comment]
Was able to replicate the issue. However, the BCO is published even though the popup says The object ID 'https://biocomputeobject.org/BCO_000316/3.0' was not found on the server.
