### ISSUE TITLE
Outreach Efforts: Tracking advertising for conference

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#345]
- Shared flyers with our collaborators: FDA, Nextflow, SevenBridges, and DNAnexus. 
- Event details have been shared with the Biochemistry department
- Emailed previous attendees from past BioCompute workshops
- Raja, Jonathon, and Jeet (from the HIVE Lab) included flyers in their class presentations
- Event has been shared on a few Bioinformatics related websites: [ISCB](https://www.iscb.org/cms_addon/events/details.php?uid=3162), [ISB](https://www.biocuration.org/forthcoming-events/)
- Contacted Georgetown Biostatistics, Bioinformatics department, but plan to follow up with them and other schools
- Currently post on our LinkedIn twice a week (Tuesday and Friday): https://www.linkedin.com/company/biocompute-partnership/?lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_all%3Bvi8QcHohTAa%2F7XbKGaL1dg%3D%3D
- Emailed GW media and Children's National media

**Comment by Kirans0615** [comment]
- Information Systems professors included flyer in class presentation
- Flyers shared around business and science buildings
- Flyers given to relating organizations and professional fraternities
- Emailed related industry companies and groups, Quanscient (multi-physics AI company), SynergiseAI (Data AI company) 
- Begun draft of more Linkedin posts
