### ISSUE TITLE
Spelling error correction 'Remove External Reference'

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/portal_userdb#347]
**Describe the bug**
Not really a bug just a spelling error in the external references of the description domain.

**To Reproduce**
1. Go to 'Builder'
2. Click on 'description domain'
3. Click on 'add external references'

**Expected behavior**
It should say 'Remove External Reference'

**Screenshots**
![References](https://github.com/biocompute-objects/portal_userdb/assets/127264259/a77b51bc-e961-4916-b96b-a98452a6301a)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by tiwa1154** [comment]
Fixed and pushed to main branch: https://github.com/biocompute-objects/portal_userdb/commit/06d5ac1a3a8c9a851b9f27ca6e7480eb47090bf6
