### ISSUE TITLE
`Last Update` display timezone 

### ISSUE THREAD

**Issue by seankim658** [biocompute-objects/portal_userdb#348]
![image](https://github.com/biocompute-objects/portal_userdb/assets/33474168/6c4c05d5-a918-45ab-bd6b-2030d415270f)

Would be nice if the frontend on the portal displayed the correct time zone aware datetime in the `Last Update` column. Right now the frontend is displaying the raw database stored value, which is in ISO 8601 format. While that format should be kept as is in the database for consistent tracking, updating, and comparisons using a standardized time format, it can be confusing on the frontend for the user if they aren't aware of how ISO 8601 format works. For example, in the above screenshot users might assume the timestamp is in a time zone aware 24 hour format when actually `14:20` in ISO 8601 refers to `10:20AM` in EDT, not `2:20PM` in EDT 24 hour format.  A good place to test timestamp conversions is this [website](https://www.timestamp-converter.com/).

**Comment by HadleyKing** [comment]
https://github.com/biocompute-objects/portal_userdb/commit/ae05fa42441706f1fe634fa60787ab98485365e7
