### ISSUE TITLE
ENCODE pipelines

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/portal_userdb#360]
- https://github.com/ENCODE-DCC/rna-seq-pipeline
- https://www.genome.gov/sites/default/files/Multimedia/Slides/ENCODE2016-ResearchAppsUsers/ENCODE2016_strattan_slides.pdf

**Comment by Kirans0615** [comment]
[The Encyclopedia of DNA elements (ENCODE):](url) data portal update (update to ENCODE ANALYSIS PIPELINES Above) 
            a. https://watermark.silverchair.com/gkx1081.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAA2YwggNiBgkqhkiG9w0BBwagggNTMIIDTwIBADCCA0gGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4_24z96nf6v82AnPAgEQgIIDGZzfc3bUABfDjiuUAimVq_WO4WgWUeBoo4U20A-6ydfuz0zeaC5qvQajtWG_MCPgSO5HU-M9TsfJ7vv2oyv8r5oEK-ILWEpBSLyNQMagOGlgC4U5beDX-df_-jteMUW4w6H27zgd3AKyC5dFrMhCxUrNpYft0YtMPNwGJIeQDSrYZua_l8fW3dn9-OVEPQkRcVzUOm_iui0-t7e1Zlx3xqfgyvbUCZZCskDqaDIjz5WllOyUKeR_5KAiy9AaeuXs8MOqtlGouMwwsSj2j9hwEOV6-awFCJwxYb9YgdIFA_WrUtUwEB7mgBb-NRYt6sHARt06jihlS7TdskNh5pZskdVj7JtHzLWeIw_WZpkXtOa3UlBxgY3bRUusLT3O-a7-mfcgJm9eAco7xZXA2KWmldJsN6hFrHf9_nCpgrQblWFxFIt2wzjRZ-OtCtwr0IQMRmvK5vyH8xrRbtSyb_EO4y8Z9WxGDJ6Ak2YKMmfr0S8I2wIZ8I5tA48sOutHeob83xh4uPQ-U0YB7NWN6PpeyQhdG2pRgGcu5X57VzuNVnnwOSR4SIZeKmxXiBnk94DcVl734cSpN8tEBGKygFy9TUYTWmtSikryrQUeg8BTheia5OOn17sRv69l2JsSzW4h3bn6FqOIJW_OA-oHmUvLlUWFzlKOkWvyEy2tE7a7pY2LLK3CM2KIbxf-nWWtmBijNPssPyAvyVZo5C2tdLjyzmEHkQKth1YBv663f721KBcRlb8JWN8HjQxySJsykpy7LC5y-a3__PVVnh1IK31GM24flWdbQUdQcFk8jQviMLQHlNYL-30vWmeqH7VVtiHpLfyl07sWW1wcSBAknZ6YTklAF7b8WVxR_-jwayar_5ZwyQ2L135piVlNOe7SW0Z-b-pQ7K0XxLrDVXJ4vjMusBrDz3FhaoTT3beqUA-fqMMlSjqp8fa2nTBeuV0LnAI_dKN7SKsNR74ty8JOJHJ0x5O0ileZ5qQt9dUWm_dfGs5MBDotxVKgM2EYNwvme5RjRuzPjRL_199xBgwBphkdb99J66COaniT1d4

**Comment by Kirans0615** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10371165/

**Comment by Kirans0615** [comment]
[ENCODE data at the ENCODE portal](https://watermark.silverchair.com/gkv1160.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAA2cwggNjBgkqhkiG9w0BBwagggNUMIIDUAIBADCCA0kGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5G6-sEgAJUbJhk3FAgEQgIIDGkR281xWUs0qlTBggVC3PJuYDxgR_AkBN4RWdEqwyzmHyUv8kDMKHdskRVSk4lCzyGAkwg3cg81tyXixjjQOHeBcttcZraZKSL6uJ2W7Z0QbjJu_at3LifjiA503JzD3uITR8Ohns-USNs5XPkZaj_LfadC5qDLjiMse8wiA0kNe3z27dsBvvnPZrP_7fNrnJFukobHSQepB3QpKSXNhHR94IUPY--2lbh1y9QTokgE8W806Ifm9PlJbwJWWgFxajMYJMwnlNbVixlgyMLOQaole54VG0IBQK5mmS67628j01yoQjN6a9VUBGcLeRzfPHJEjekUOTl7MA2NCQjap80GF7N6GqZo67bhcRaJys3xy0udz6eoRvSPoyGOIzaLmQ92cHpqqK-hsG5fTU7P8vK9D8al1J4uJGmys1GBbpXlOvYQwHwu2-Pbag_2GqZS9MywioeII0fuZx6tHzDMITs_NYyM2jJjIAeJetHI-zm5v6NHOSPknSRLmDnSNz6dJY_P9jAFI0eVvjts-Dr6QAYnuGDNIKaQ86HXEhTa_ozcLcrMNiQUZCPbo55lzW1tNkSjUzzhTz7sK25JevXDfUo2Mxw068A53F8gi7oXnbquueEGN-9eL4tfdxmnTGv0f5oR0qciLBwRZGUfg3OzQwCganFuWod-lMrqeYywunJnRufAA585A53gZIdw9aS765VdHo6H2B6iZ25qefuGjvbtmNCYe5wbbY5iXzaxDFBp9fSQlYo5v4s_bnFDcmPy4BgXMPsuw-kELtoHGxS_ZF2Dj5welsYAc98RXwzSFLW6EL-mtiCgQF4QwDBJP5P3e5J3myzsl7c1muovaOUZtFVEDJ0G0FM0lgdq_d9lFnhaDvH2AWHLD9_iTBP94inIlygx6PLdeyQ6xshCMw-wUxPaK7OtRkI2Y_nGg4Vwfcf6CVtZycE48rtH6Da8HR1x_bBn2vwSxxyFC64mRYbHq66sdtR4Oe60og8cAGQ9bRzND-hhAk4j5GKNnTqaRJvFPgZK9HvqC9cEuYnQZtEhBenCVFoiOOp-Dilrd)

**Comment by ChinweokeO** [comment]
https://www.encodeproject.org/pipelines/

**Comment by tiwa1154** [comment]
https://docs.google.com/document/d/1VSzMim3m8J4HcDgBiWp6J83Wog-J4vH2AwwbeOSpo8Y/edit#heading=h.xb6rawv7l7zs
