### ISSUE TITLE
GTEX RNA-seq pipeline

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/portal_userdb#361]
- https://github.com/broadinstitute/gtex-pipeline/tree/master/rnaseq

**Comment by Kirans0615** [comment]
-RNA-Seq Data BAM Files with the Java program ubu.jar
            a. https://github.com/mozack/ubu
-Analysis Pipeline
            a. https://github.com/mskcc/RNAseqDB/blob/master/configuration/tissue-conf.txt (see figure in article for more)
-https://www.nature.com/articles/sdata201861

**Comment by tiwa1154** [comment]
https://docs.google.com/document/d/1VSzMim3m8J4HcDgBiWp6J83Wog-J4vH2AwwbeOSpo8Y/edit#heading=h.xb6rawv7l7zs
