### ISSUE TITLE
GATK workflows

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/portal_userdb#362]
https://github.com/gatk-workflows
https://github.com/gatk-workflows/gatk4-rnaseq-germline-snps-indels

**Comment by Kirans0615** [comment]
Pipeline for somatic variant discovery
-https://bitbucket.org/BBDA-UNIBO/wes-pipeline 
            a. The alignments were submitted to local realignment around INDELs and base quality score recalibration (BQSR) by using the Genome Analysis Toolkit (GATK) version 3.0
            b. https://link.springer.com/article/10.1186/s12859-016-1190-7

**Comment by Kirans0615** [comment]
https://ieeexplore.ieee.org/abstract/document/7359893
(Cluster-based Apache Spark implementation of the GATK DNA analysis pipeline)
