### ISSUE TITLE
BCOs within the BCO prefix are not saving. Error Code 500. 

### ISSUE THREAD

**Issue by ubhuiyan** [biocompute-objects/portal_userdb#370]
**Describe the bug**

**To Reproduce**
1. Go to 'https://biocomputeobject.org/'
2. Click on 'Builder'
3. Select down to 'biocomputeobject.org'
4. Input basic information needed for the provenance domain
5. Select "Next"
6. Select "Save Draft BCO" 

**Expected behavior**
The BCO draft to save and generate a BCO link for the specific BCO. 

**Screenshots**
![Screenshot 2024-05-22 at 1 24 36 PM](https://github.com/biocompute-objects/portal_userdb/assets/90285310/5ee47145-626a-48d9-af8c-9551a6702d2c)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Chrome v.126.0.6478.8

**Comment by tiwa1154** [comment]
same issue #369
