### ISSUE TITLE
Search results show some number of hits, but no results are populated

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal_userdb#375]
Search results show some number of hits, but no results are populated (see screenshot)

![searchResults](https://github.com/biocompute-objects/portal_userdb/assets/12193741/68705640-c0cd-48e0-a46d-91a400ef506a)

**Comment by tiwa1154** [comment]
@HadleyKing Is this fixed?

**Comment by tiwa1154** [comment]
Fixed.
