### ISSUE TITLE
Nextflow pipelines

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/portal_userdb#389]
- [ ] Check for GDC pipeline in nf-core or make one
- [ ] Check for trainings/workshops for learning purposes and share with the team

**Comment by tiwa1154** [comment]
https://bioinformaticsworkbook.org/dataAnalysis/nextflow/02_creatingAworkflow.html#gsc.tab=0
Bioinformatics Workbook
[Creating a NextFlow workflow](https://bioinformaticsworkbook.org/dataAnalysis/nextflow/02_creatingAworkflow.html#gsc.tab=0)
A workbook to help scientists working on bioinformatics projects (719 kB)
https://bioinformaticsworkbook.org/dataAnalysis/nextflow/02_creatingAworkflow.html#gsc.tab=0






[10:34](https://hivelab.slack.com/archives/D05G20HK9PV/p1723732495692279)
https://www.nextflow.io/docs/latest/config.html
[10:37](https://hivelab.slack.com/archives/D05G20HK9PV/p1723732621890159)
https://docs.google.com/document/d/1XrjZ0z3BaM-vV6yBvxP_6_pqCJ3OhB3pNOKzWRyeqIU/edit?usp=sharing
New
[10:37](https://hivelab.slack.com/archives/D05G20HK9PV/p1723732676525219)
https://docs.google.com/document/d/1VSzMim3m8J4HcDgBiWp6J83Wog-J4vH2AwwbeOSpo8Y/edit#heading=h.q0mh6udlqb28

**Comment by tiwa1154** [comment]
- [ ] Replicate RNA-seq workfliw from paper and update BCO in DB #419 
- [ ] Potential BCO workflows #359

**Comment by tiwa1154** [comment]
Messaged Kiran to ask for blockers

**Comment by tiwa1154** [comment]
https://nf-co.re/viralrecon/2.6.0/
