### ISSUE TITLE
Comparison of two workflows

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal_userdb#396]
Implementation of a programmatic tool that will compare the metadata of the two different versioned workflows.

**Comment by kee007ney** [comment]
Might be ok, but I worry that it's too general. One of the Seans' tools is more BCO-specific and might be better suited to BCO diff-ing?

**Comment by HadleyKing** [comment]
https://test.portal.biochemistry.gwu.edu/api/docs/#/BCO%20Management/api_bco_compare
