### ISSUE TITLE
Embargo Saving Issue

### ISSUE THREAD

**Issue by Kirans0615** [biocompute-objects/portal_userdb#403]
**Describe the bug**
After inserting embargo start and end time and then clicking next, everything in the domain saves except embargo start and end time, but then works after inserting it again and clicking next again

**To Reproduce**
1. Go to 'Provenance Domain'
2. Click on 'Embargo start and end time'
3. Insert information
4. Click next

**Expected behavior**
Save after clicking next once (like the other items in the domain)

**Comment by tiwa1154** [comment]
I wasn't able to replicate the issue. Maybe @ChinweokeO can try to replicate?

**Comment by ChinweokeO** [comment]
Yes, the same thing happens for me. It saves on the second time I enter it in. It also doesn't give you an option to hit next when you remove Embargo

**Comment by tiwa1154** [comment]
@Kirans0615 @ChinweokeO are you both using Chrome?

**Comment by ChinweokeO** [comment]
Yes, I am.

**Comment by tiwa1154** [comment]
PR: https://github.com/biocompute-objects/portal_userdb/pull/425
