### ISSUE TITLE
Script Driver and Environment Variables Saving Issue

### ISSUE THREAD

**Issue by Kirans0615** [biocompute-objects/portal_userdb#404]
**Describe the bug**
When shell is put into the script driver section of the execution domain it does not save on the builder. But it does save on the Raw JSON review. When you validate the BCO it says their is not script driver. This issue exists on PRD and TST.

**To Reproduce**
1. Go to 'Execution Domain'
2. Click on 'Script Driver.' (Or Environment Variables)
3. Item shell or whatever applies to your BCO

**Expected behavior**
It is supposed to save after clicking next the first time.

**Comment by tiwa1154** [comment]
I can only replicated Script Driver not saving after clicking Next but not Environment Variables.

**Comment by tiwa1154** [comment]
Script Driver is saved in the RAW JSON View but not in the domain page

**Comment by tiwa1154** [comment]
Also exist on prd

**Comment by tiwa1154** [comment]
@Kirans0615 @ChinweokeO For the environment variable not saving issue, did you guys click on "add" after entering the values?

**Comment by tiwa1154** [comment]
https://github.com/biocompute-objects/portal_userdb/pull/422

**Comment by tiwa1154** [comment]
PR approved and merged.
