### ISSUE TITLE
Add Scoring FAQ

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#446]

**Comment by Kirans0615** [comment]
Finished put onto wiki under it's own section within the FAQ page

**Comment by Kirans0615** [comment]
Finished put onto wiki under it's own section within the FAQ page

**Comment by tiwa1154** [comment]
Kiran added to FAQ in https://wiki.biocomputeobject.org/FAQs#BCO_Scoring_System
