### ISSUE TITLE
Draft Tutorial

### ISSUE THREAD

**Issue by kee007ney** [biocompute-objects/portal_userdb#47]

**Comment by tiwa1154** [comment]
Nearly done for the general tutorial. Prefix is broken, need to go back to revise the prefix section. Current version can be found at https://gwu0.sharepoint.com/:w:/r/sites/BioCompute-GRP/Shared%20Documents/Tutorials/BioCompute%20Tutorial.docx?d=wa5f244765c194bf680d2efad5abb3d73&csf=1&web=1&e=uFyUyk

**Comment by kee007ney** [comment]
Waiting on prefixes, estimated ready early next week.

**Comment by tiwa1154** [comment]
Update tutorial: https://gwu0.sharepoint.com/:w:/r/sites/BioCompute-GRP/Shared%20Documents/Tutorials/BioCompute%20Tutorial.docx?d=wa1f98c7c2ce34c33a531278e188a6761&csf=1&web=1&e=r0kNdy. Updated prefix registration, groups/permission.

**Comment by kee007ney** [comment]
Just need to update wiki page.

**Comment by tiwa1154** [comment]
Updated Wiki page and uploaded a PDF to wiki too
