### ISSUE TITLE
Keep page controls on a static sidebar

### ISSUE THREAD

**Issue by kee007ney** [biocompute-objects/portal_userdb#56]
In the BCO viewer, one can scroll very far down in some cases to get to the bottom, where controls like "download" and "publish" are.

Suggest decoupling them from the main page and adding them to sidebar (where you can pick which domain you want to view), and making that sidebar sticky (e.g. [with CSS](https://stackoverflow.com/questions/13337646/scroll-inside-of-a-fixed-sidebar) or however else).

**Comment by kee007ney** [comment]
"Sticky" sidebar that stays with you as you scroll down.

**Comment by HadleyKing** [comment]
42c2f7079775a0cb993fe7a4aceb54a37d11398e
