### ISSUE TITLE
Group name disappeared on Groups/permissions page

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/portal_userdb#86]
**Describe the bug**
I registered a prefix called "Prete" (prefix test) and was testing on group modification. After clicking on "Update Group" without making any changes, the prete_drafter and prete_publisher disappeared. However, they have come back after a few minutes. 

Using Firefox, Macbook.

**Comment by HadleyKing** [comment]
@tiwa1154 is this still an issue?
